services:
  mnote-backend:
    image: xxxsen/mnote:latest
    container_name: mnote-backend
    volumes:
      - ./config:/config  
    expose:
      - "8080"
    command: run --config=/config/config.json  

  mnote-web:
    image: xxxsen/mnote-web:latest
    container_name: mnote-web
    environment:
      - NEXT_PUBLIC_API_BASE=http://mnote-backend:8080/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - mnote-backend

networks:
  mnote:

volumes:
  backend-data:
