services:
  mnote-backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: mnote-backend
    volumes:
      - ./mnote:/config
      - ./data:/data
    expose:
      - "8080"
    networks:
      - mnote
    command: run --config=/config/config.json
    restart: always

  mnote-web:
    build:
      context: ../web
      dockerfile: Dockerfile
    container_name: mnote-web
    expose:
      - "3000"
    depends_on:
      - mnote-backend
    networks:
      - mnote
    restart: always

  mnote-gateway:
    image: nginx:alpine
    container_name: mnote-gateway
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - mnote-web
      - mnote-backend
    networks:
      - mnote
    restart: always

networks:
  mnote:
    name: mnote_network
